
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: nryotaro/clangcmake:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "LICENSE" }}
      - run:
          name: run tests
          command: |
            make
      - save_cache:
          paths:
            - ./build
          key: v1-dependencies-{{ checksum "LICENSE" }}
